### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by naeemshaikh90** [dcordero/TvOSTextViewer#1]
![screen shot 2017-02-16 at 3 55 23 pm](https://cloud.githubusercontent.com/assets/10736853/23017478/6b1ed43c-f460-11e6-9f9a-2ba3bb5a3f34.png)

**Comment by naeemshaikh90** [comment]
Hey @dcordero nice work, please take a look at this before I can [approve your PR](https://github.com/vsouza/awesome-ios/pull/1473)

**Comment by dcordero** [comment]
Fixed ✅
